export const investmentBrokerages = [
  "Vanguard",
  "Fidelity Investments",
  "Charles Schwab",
  "Merrill Lynch",
  "Morgan Stanley",
  "Goldman Sachs",
  "E*TRADE",
  "TD Ameritrade",
  "Interactive Brokers",
  "Robinhood",
  "Webull",
  "Edward Jones",
  "Raymond James",
  "LPL Financial",
  "UBS Financial Services",
  "Wells Fargo Advisors",
  "J.P. Morgan Private Bank",
  "Citigroup",
  "Credit Suisse",
  "Deutsche Bank Wealth Management",
  "HSBC Private Banking",
  "Barclays Wealth and Investment Management",
  "BNP Paribas Wealth Management",
  "Northern Trust",
  "RBC Wealth Management",
  "Santander Private Banking",
  "Scottrade",
  "T. Rowe Price",
  "Ameriprise Financial",
  "AXA Advisors",
  "BlackRock",
  "Capital One Investing",
  "Betterment",
  "Wealthfront",
  "Acorns",
  "SigFig",
  "Ally Invest",
  "Sofi Invest",
  "Citi Personal Wealth Management",
  "Baird",
  "Janney Montgomery Scott",
  "Stifel",
  "Jefferies",
  "BMO Wealth Management",
  "Voya Financial",
  "Principal Financial Group",
  "Franklin Templeton Investments",
  "John Hancock",
  "State Street Global Advisors",
  "Legg Mason",
  "Invesco",
  "Affiliated Managers Group",
  "Ameritas Investment Corp",
  "BB&T Investments",
  "Cambridge Investment Research",
  "Cetera Advisor Networks",
  "Commonwealth Financial Network",
  "Federated Investors",
  "Fifth Third Bank",
  "First Command Financial Planning",
  "First Republic Investment Management",
  "FolioFn",
  "Investec Wealth & Investment",
  "KCG Holdings",
  "Lincoln Financial Advisors",
  "M&T Bank Corporation",
  "MetLife",
  "National Planning Corporation",
  "Natixis Global Asset Management",
  "Navy Federal Brokerage Services",
  "Nest Wealth",
  "New York Life Investment Management",
  "Northwestern Mutual",
  "OppenheimerFunds",
  "OptionsHouse",
  "PIMCO",
  "PNC Financial Services",
  "Prudential Financial",
  "Putnam Investments",
  "Questrade",
  "Raymond James Financial Services",
  "Russell Investments",
  "SagePoint Financial",
  "Salomon Smith Barney",
  "Santander Investment Securities",
  "Schroders",
  "ShareBuilder",
  "SIPC",
  "SunTrust Banks",
  "Susquehanna International Group",
  "Synovus",
  "TIAA-CREF",
  "Transamerica",
  "UBS",
  "USAA",
  "Valic",
  "Virtu Financial",
  "Waddell & Reed",
  "Zacks Investment Research",
  "Zurich Scudder Investments",
];
