export const investmentBrokerages = [
  "Acorns",
  "Affiliated Managers Group",
  "Ally Invest",
  "Ameriprise Financial",
  "Ameritas Investment Corp",
  "AXA Advisors",
  "Baird",
  "Barclays Wealth and Investment Management",
  "BB&T Investments",
  "Betterment",
  "BlackRock",
  "BMO Wealth Management",
  "BNP Paribas Wealth Management",
  "Cambridge Investment Research",
  "Capital One Investing",
  "Charles Schwab",
  "Cetera Advisor Networks",
  "Citi Personal Wealth Management",
  "Citigroup",
  "Commonwealth Financial Network",
  "Credit Suisse",
  "Deutsche Bank Wealth Management",
  "E-TRADE",
  "Edward Jones",
  "Federated Investors",
  "Fidelity Investments",
  "Fifth Third Bank",
  "First Command Financial Planning",
  "First Republic Investment Management",
  "FolioFn",
  "Franklin Templeton Investments",
  "Goldman Sachs",
  "HSBC Private Banking",
  "Interactive Brokers",
  "Investec Wealth & Investment",
  "Invesco",
  "J.P. Morgan Private Bank",
  "Janney Montgomery Scott",
  "Jefferies",
  "John Hancock",
  "KCG Holdings",
  "Legg Mason",
  "Lincoln Financial Advisors",
  "LPL Financial",
  "M&T Bank Corporation",
  "Merrill Lynch",
  "MetLife",
  "Morgan Stanley",
  "Natixis Global Asset Management",
  "Navy Federal Brokerage Services",
  "Nest Wealth",
  "New York Life Investment Management",
  "Northern Trust",
  "Northwestern Mutual",
  "OppenheimerFunds",
  "OptionsHouse",
  "PIMCO",
  "PNC Financial Services",
  "Principal Financial Group",
  "Prudential Financial",
  "Putnam Investments",
  "Questrade",
  "Raymond James",
  "Raymond James Financial Services",
  "RBC Wealth Management",
  "Robinhood",
  "Russell Investments",
  "SagePoint Financial",
  "Salomon Smith Barney",
  "Santander Investment Securities",
  "Santander Private Banking",
  "Schroders",
  "Scottrade",
  "ShareBuilder",
  "SigFig",
  "SIPC",
  "Sofi Invest",
  "State Street Global Advisors",
  "Stifel",
  "SunTrust Banks",
  "Susquehanna International Group",
  "Synovus",
  "T. Rowe Price",
  "TD Ameritrade",
  "TIAA-CREF",
  "Transamerica",
  "UBS",
  "UBS Financial Services",
  "USAA",
  "Valic",
  "Vanguard",
  "Virtu Financial",
  "Voya Financial",
  "Waddell & Reed",
  "Wealthfront",
  "Webull",
  "Wells Fargo Advisors",
  "Zacks Investment Research",
  "Zurich Scudder Investments",
];
